/**
 * This module defines the {@link MwbotError} class, which is used to standardize
 * error handling. See {@link MwbotError} for details.
 *
 * Note that internal exceptions are caught by the built-in Error class.
 *
 * @module
 */

import type { ApiResponse, ApiResponseError } from './api_types.js';
import { cloneDeep, isPlainObject } from './Util.js';
import type { ConfigData } from './Mwbot.js';

// Imported only for docs
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { Mwbot } from './Mwbot.js';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { ModificationPredicate } from './Wikitext.js';

/**
 * Custom error class for {@link Mwbot}, extending the built-in `Error` class.
 * This class is exported for use with the `instanceof` operator.
 *
 * This error class is used throughout {@link Mwbot} to standardize error handling,
 * ensuring that all errors and rejected Promises include a stack trace for easier
 * debugging.
 *
 * For a list of error codes, see {@link MwbotErrorCodes}.
 */
export class MwbotError<K extends keyof MwbotErrorCodes = keyof MwbotErrorCodes> extends Error {

	/**
	 * The type of the error.
	 */
	type: K;
	/**
	 * The code of the error.
	 */
	code: string;
	/**
	 * The information of the error.
	 */
	info: string;
	/**
	 * Additional data of the error.
	 */
	data?: MwbotErrorData;

	/**
	 * Creates a new instance.
	 *
	 * @param type The type of the error.
	 * @param config The error details object. This object must contain `code` and `info`
	 * properties. Other properties are merged into the `data` property of the new instance.
	 * @param data Optional object to initialize the `data` property with.
	 * @throws {TypeError} If `config` is not a plain object.
	 */
	constructor(
		type: K,
		config: K extends 'api'
			? ApiResponseError
			: Omit<ApiResponseError, 'code'> & { code: keyof MwbotErrorCodes[K] },
		data?: MwbotErrorData
	) {
		if (!isPlainObject(config)) {
			throw new TypeError('MwbotError.constructor only accepts a plain object.');
		}

		super(config.info);
		this.name = 'MwbotError';
		this.type = type;
		this.code = config.code;
		this.info = config.info;
		this.data = data;

		// Ensure proper stack trace capture
		if (Error.captureStackTrace) {
			Error.captureStackTrace(this, MwbotError);
		}
	}

	/**
	 * Creates a new instance from an API error response.
	 *
	 * @param response An API response with the `error` or `errors` property.
	 * @returns A new MwbotError instance.
	 */
	static newFromResponse(
		response: Required<Pick<ApiResponse, 'error'>> | Required<Pick<ApiResponse, 'errors'>>
	): MwbotError<'api'> {
		// Construct a `config` object for the constructor, which must include `code` and `info`
		let config: ApiResponseError;

		if ('errors' in response) {
			const firstError = response.errors?.[0];
			const info =
				firstError?.['*'] || // formatversion=1
				// formatversion=2
				firstError?.text || // errorformat=wikitext, errorformat=plaintext
				firstError?.html || // errorformat=html
				firstError?.key || // errorformat=raw
				'Unknown error.';

			// TODO: This is in fact `ApiResponseErrors & { info: string }`. Only extract code
			// and info when we drop support for MwbotErrorData.error.
			config = Object.assign({}, firstError, { info });
		} else {
			config = response.error;
		}

		// Ensure code and info are always defined. Although MediaWiki API error
		// responses normally include both fields, malformed responses may not.
		// The fallback values below are used by the MediaWiki Action API itself.
		config.code ??= 'unknownerror-nocode';
		config.info ??= 'Unknown error.';

		return new MwbotError('api', config, {
			response,
			error: config, // deprecated
		});
	}

	/**
	 * Updates the error code.
	 *
	 * @param code The new error code.
	 * @returns The current instance for chaining.
	 */
	setCode(
		code: K extends 'api' ? string : keyof MwbotErrorCodes[K]
	): this {
		this.code = code;
		return this;
	}

	/**
	 * Updates the error information.
	 *
	 * @param info The new error information.
	 * @returns The current instance for chaining.
	 */
	setInfo(info: string): this {
		this.info = info;
		this.message = info;
		return this;
	}

	/**
	 * @hidden
	 */
	_clone(): this {
		const cloned = new MwbotError(
			this.type,
			{
				code: this.code,
				info: this.info,
			} as any,
			this.data ? cloneDeep(this.data) : undefined
		) as this;

		cloned.stack = this.stack;

		return cloned;
	}

}

/**
 * This interface defines error types and error codes generated by `mwbot-ts`.
 *
 * The string values are descriptions of the error codes and not referenced or used in the source code.
 */
export interface MwbotErrorCodes {
	/**
	 * Marks errors from HTTP requests returned by the MediaWiki API.
	 *
	 * This property is always an empty object because the API itself defines the error codes.
	 */
	api: { /* empty */ };
	/**
	 * Marks errors of HTTP requests, generated by `mwbot-ts`.
	 */
	api_mwbot: {
		// General errors
		invalidformat: 'Not using "format=json" in request parameters.';
		anonymous: 'Anonymous users are limited to non-write requests.';
		loginfailed: 'Failed to log in.';
		nopermission: 'You do not have permission to perform this action.';
		botdenied: 'The target page has opted out of edits by this bot or the message types it delivers.';
		// Used in the catch block of Mwbot._init
		badauth: 'Failed to authenticate the client as a registered user in Mwbot.init.';
		badvars: 'Failed to initialize wg-variables in Mwbot.init.';
		// Used in the catch block of Mwbot._request
		http: 'Encountered an HTTP request error that is not mapped to a specific error code.';
		aborted: 'Request aborted by the user.';
		notfound: 'Page not found (404).';
		timeout: 'Request timeout (408) or Gateway timeout (504).';
		baduri: 'URI too long (414).';
		ratelimited: 'Too many requests (429).';
		servererror: 'Internal server error (500).';
		badgateway: 'Bad gateway (502)';
		serviceunavailable: 'Service Unavailable (503)';
		// Used in the then block of Mwbot._request
		empty: 'OK response but empty result.';
		invalidjson: 'No valid JSON response.';
		// Used in the then block of Mwbot.getToken
		badnamedtoken: 'An unknown token name was specified for Mwbot.getToken.';
		// Used in Mwbot.prepEdit or in read() or edit()-related methods
		invalidtitle: 'The given title cannot be processed because it is invalid.';
		emptytitle: 'The given title cannot be processed because it is empty.';
		interwikititle: 'The given title cannot be processed because it is interwiki.';
		specialtitle: 'The given title cannot be processed because it is in the Special or Media namespace.';
		pagemissing: 'The requested page does not exist.';
		editfailed: 'The edit attempt failed with a `result: "Failure"` code.';
	};
	/**
	 * Marks fatal exceptions attributed to the user's source code.
	 */
	fatal: {
		// General errors
		typemismatch: 'There is an issue with the type of a variable.';
		nourl: 'No valid API endpoint is provided.';
		invalidcreds: 'There is an issue with the credential information passed to Mwbot.';
		emptyinput: 'A required input value is empty.';
		internal: 'An unexpected internal error occurred.';
		// Used in Mwbot.createBatchArray
		invalidsize: 'The "batchSize" argument for massRequest() or continuedRequest() is invalid.';
		fieldmismatch: 'API parameters passed to massRequest() or continuedRequest() involve unmatching multi-value fields.';
		nofields: 'No multi-value fields are provided for massRequest() or continuedRequest().';
		// Used in Mwbot.continuedRequest
		invalidlimit: 'The "limit" argument for continuedRequest() is invalid.';
		// Used in Wikitext.modify
		invalidtype: 'Wikitext.modify does not support this expression type.';
		// Used in Title
		unparsabletitle: 'The title string passed to Title.constructor cannot be parsed.';
	};
}

/**
 * Interface for the {@link MwbotError.data} property.
 */
export interface MwbotErrorData {
	/**
	 * @deprecated Use {@link response} instead.
	 */
	error?: Record<string, any>;
	/**
	 * Full API response associated with the error.
	 */
	response?: ApiResponse;
	/**
	 * Present when {@link Mwbot.init} fails to initialize certain `wg`-variables.
	 */
	keys?: (keyof ConfigData)[];
	/**
	 * The full Axios response object. Present for `api_mwbot` errors with a code of
	 * `http` (including specific types such as `timeout (408)`), `empty`, or `invalidjson`.
	 */
	axios?: Record<string, any>;
	/**
	 * Present when the error involves a processed page title, such as in {@link Mwbot.read}.
	 */
	title?: string;
	/**
	 * Present when the callback return value from {@link Mwbot.edit} is invalid.
	 */
	transformed?: unknown;
	/**
	 * Present when a method receives an array parameter (e.g., {@link Mwbot.purge}) containing
	 * values of incorrect types.
	 */
	invalid?: unknown[];
	/**
	 * Present when a {@link ModificationPredicate} returns a value that is neither a string nor `null`.
	 * This property records the index and the corresponding unexpected value encountered.
	 */
	modified?: { [index: string]: unknown };
}