import { describe } from 'mocha';
import { testMwbotProperties } from './MwbotTest/MwbotTest-properties.js';
import { testMwbotConstructor } from './MwbotTest/MwbotTest-constructor.js';
import { testMwbotState } from './MwbotTest/MwbotTest-state.js';
import { testMwbotExceptions } from './MwbotTest/MwbotTest-exceptions.js';
import { testMwbotConfig } from './MwbotTest/MwbotTest-config.js';
import { testMwbotRequest } from './MwbotTest/MwbotTest-request.js';
import { testMwbotRequestHelpers } from './MwbotTest/MwbotTest-request-helpers.js';
import { testMwbotRequestBatch } from './MwbotTest/MwbotTest-request-batch.js';
import { testMwbotRequestToken } from './MwbotTest/MwbotTest-request-token.js';
import { testMwbotRequestEdit } from './MwbotTest/MwbotTest-edit.js';
import { testMwbotRequestOptions } from './MwbotTest/MwbotTest-request-options.js';
import { testMwbotRequestAuth } from './MwbotTest/MwbotTest-request-auth.js';
import { testMwbotRequestActions } from './MwbotTest/MwbotTest-request-actions.js';
import { testMwbotRequestAdmin } from './MwbotTest/MwbotTest-request-admin.js';
import { testMwbotRequestQuery } from './MwbotTest/MwbotTest-request-query.js';

describe('Mwbot', function () {
	testMwbotProperties();
	testMwbotConstructor();
	testMwbotState();
	testMwbotExceptions();
	testMwbotConfig();
	testMwbotRequest();
	testMwbotRequestHelpers();
	testMwbotRequestBatch();
	testMwbotRequestToken();
	testMwbotRequestEdit();
	testMwbotRequestAuth();
	testMwbotRequestOptions();
	testMwbotRequestActions();
	testMwbotRequestAdmin();
	testMwbotRequestQuery();
});
