import { describe } from 'mocha';
import { testMwbotProperties } from './MwbotTest-properties.js';
import { testMwbotConstructor } from './MwbotTest-constructor.js';
import { testMwbotState } from './MwbotTest-state.js';
import { testMwbotExceptions } from './MwbotTest-exceptions.js';
import { testMwbotConfig } from './MwbotTest-config.js';
import { testMwbotRequest } from './MwbotTest-request.js';
import { testMwbotRequestHelpers } from './MwbotTest-request-helpers.js';
import { testMwbotRequestBatch } from './MwbotTest-request-batch.js';
import { testMwbotRequestToken } from './MwbotTest-request-token.js';
import { testMwbotEdit } from './MwbotTest-edit.js';
import { testMwbotOptions } from './MwbotTest-request-options.js';
import { testMwbotRequestAuth } from './MwbotTest-request-auth.js';
import { testMwbotRequestActions } from './MwbotTest-request-actions.js';
import { testMwbotRequestAdmin } from './MwbotTest-request-admin.js';

describe('Mwbot', function () {
	testMwbotProperties();
	testMwbotConstructor();
	testMwbotState();
	testMwbotExceptions();
	testMwbotConfig();
	testMwbotRequest();
	testMwbotRequestHelpers();
	testMwbotRequestBatch();
	testMwbotRequestToken();
	testMwbotEdit();
	testMwbotRequestAuth();
	testMwbotOptions();
	testMwbotRequestActions();
	testMwbotRequestAdmin();
});